-- Profiles table to store user information and roles
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
  full_name TEXT,
  role TEXT CHECK (role IN ('admin', 'validator')) DEFAULT 'validator',
  is_approved BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Exercises table for math exercises (Targeting 12,000 exercises)
CREATE TABLE IF NOT EXISTS public.exercises (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content JSONB NOT NULL,
  status TEXT CHECK (status IN ('pending', 'validated', 'rejected')) DEFAULT 'pending',
  validated_by UUID REFERENCES public.profiles(id),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Dedicated locks table for real-time concurrency control
CREATE TABLE IF NOT EXISTS public.locks (
  exercise_id BIGINT REFERENCES public.exercises(id) PRIMARY KEY,
  locked_by UUID REFERENCES public.profiles(id) NOT NULL,
  locked_at TIMESTAMPTZ DEFAULT NOW(),
  expires_at TIMESTAMPTZ DEFAULT (NOW() + INTERVAL '15 minutes')
);


-- Audit logs for tracking changes
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id),
  action TEXT NOT NULL,
  target_id BIGINT,
  details JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exercises ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- Policies for Profiles
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles
  FOR SELECT USING (true);

CREATE POLICY "Users can update own profile." ON public.profiles
  FOR UPDATE USING (auth.uid() = id);

-- Policies for Exercises
CREATE POLICY "Exercises are viewable by authenticated users." ON public.exercises
  FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Validators can update exercises if approved." ON public.exercises
  FOR UPDATE USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid() AND is_approved = TRUE
    )
  );

-- Policies for Locks
CREATE POLICY "Locks are viewable by authenticated users." ON public.locks
  FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Users can create/delete their own locks." ON public.locks
  FOR ALL USING (auth.uid() = locked_by);

-- Policies for Audit Logs
CREATE POLICY "Audit logs are viewable by admins only." ON public.audit_logs
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid() AND role = 'admin'
    )
  );

CREATE POLICY "Authenticated users can insert audit logs." ON public.audit_logs
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

